version: "3"
services:

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes

  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_USERS=dev
      - LDAP_PASSWORDS=dev

  kowl:
    image: docker.redpanda.com/redpandadata/console
    environment:
      KAFKA_BROKERS: kafka:9092
    ports:
      - 8094:8080

  auth-proxy-ldap:
    image: gimral/apache-auth-proxy:1.0
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AUTH_TYPE=ldap
    environment:
      - BACKEND_URL=http://kowl:8080
      - SESSION_SECRET=our_secret
      - LDAP_URL=ldap://openldap:1389/dc=example,dc=org?uid?sub?(objectClass=*)
      - LDAP_BIND_DN=cn=admin,dc=example,dc=org
      - LDAP_BIND_PASSWORD=admin
    ports:
      - 8095:80

  auth-proxy-basic:
    image: gimral/apache-auth-proxy:1.1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AUTH_TYPE=file
    environment:
      - BACKEND_URL=http://kowl:8080
      - SESSION_SECRET=our_secret
      - USER_NAME=admin
      - PASSWORD=admin
    ports:
      - 8096:80
